"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EVENT_END_INDEX_CHANGED = exports.EVENT_SHIFTED = exports.EVENT_SLIDE_KEYDOWN = exports.EVENT_LAZYLOAD_LOADED = exports.EVENT_AUTOPLAY_PAUSE = exports.EVENT_AUTOPLAY_PLAYING = exports.EVENT_AUTOPLAY_PLAY = exports.EVENT_NAVIGATION_MOUNTED = exports.EVENT_PAGINATION_UPDATED = exports.EVENT_PAGINATION_MOUNTED = exports.EVENT_ARROWS_UPDATED = exports.EVENT_ARROWS_MOUNTED = exports.EVENT_DESTROY = exports.EVENT_OVERFLOW = exports.EVENT_SCROLLED = exports.EVENT_SCROLL = exports.EVENT_DRAGGED = exports.EVENT_DRAGGING = exports.EVENT_DRAG = exports.EVENT_RESIZED = exports.EVENT_RESIZE = exports.EVENT_UPDATED = exports.EVENT_REFRESH = exports.EVENT_HIDDEN = exports.EVENT_VISIBLE = exports.EVENT_INACTIVE = exports.EVENT_ACTIVE = exports.EVENT_CLICK = exports.EVENT_MOVED = exports.EVENT_MOVE = exports.EVENT_READY = exports.EVENT_MOUNTED = void 0;
exports.EVENT_MOUNTED = 'mounted';
exports.EVENT_READY = 'ready';
exports.EVENT_MOVE = 'move';
exports.EVENT_MOVED = 'moved';
exports.EVENT_CLICK = 'click';
exports.EVENT_ACTIVE = 'active';
exports.EVENT_INACTIVE = 'inactive';
exports.EVENT_VISIBLE = 'visible';
exports.EVENT_HIDDEN = 'hidden';
exports.EVENT_REFRESH = 'refresh';
exports.EVENT_UPDATED = 'updated';
exports.EVENT_RESIZE = 'resize';
exports.EVENT_RESIZED = 'resized';
exports.EVENT_DRAG = 'drag';
exports.EVENT_DRAGGING = 'dragging';
exports.EVENT_DRAGGED = 'dragged';
exports.EVENT_SCROLL = 'scroll';
exports.EVENT_SCROLLED = 'scrolled';
exports.EVENT_OVERFLOW = 'overflow';
exports.EVENT_DESTROY = 'destroy';
exports.EVENT_ARROWS_MOUNTED = 'arrows:mounted';
exports.EVENT_ARROWS_UPDATED = 'arrows:updated';
exports.EVENT_PAGINATION_MOUNTED = 'pagination:mounted';
exports.EVENT_PAGINATION_UPDATED = 'pagination:updated';
exports.EVENT_NAVIGATION_MOUNTED = 'navigation:mounted';
exports.EVENT_AUTOPLAY_PLAY = 'autoplay:play';
exports.EVENT_AUTOPLAY_PLAYING = 'autoplay:playing';
exports.EVENT_AUTOPLAY_PAUSE = 'autoplay:pause';
exports.EVENT_LAZYLOAD_LOADED = 'lazyload:loaded';
/** @internal */
exports.EVENT_SLIDE_KEYDOWN = 'sk';
exports.EVENT_SHIFTED = 'sh';
exports.EVENT_END_INDEX_CHANGED = 'ei';
